name = "memos-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-06-01"

compatibility_flags = ["nodejs_compat"]

[vars]
LOG_LEVEL = "info"
BASE_URL = "http://127.0.0.1:8787"

# Secrets - set via wrangler secret put
# JWT_SECRET
# R2_ACCOUNT_ID  
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
# R2_BUCKET

[[d1_databases]]
binding = "DB"
database_name = "memos"
database_id = "06f11440-658a-46af-81bd-1bfbed1f7daa"  # 替换为您的实际数据库ID

[env.staging]
name = "memos-cloudflare-staging"

[env.production]
name = "memos-cloudflare-production" 