name = "memos-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-06-01"

compatibility_flags = ["nodejs_compat"]

[vars]
LOG_LEVEL = "info"
BASE_URL = "https://memos-cloudflare.haitai.workers.dev"

# Secrets - set via wrangler secret put
# JWT_SECRET
# R2_ACCOUNT_ID  
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
# R2_BUCKET

[[d1_databases]]
binding = "DB"
database_name = "memos"
database_id = "f21ca97f-e7a6-4588-ac6e-8e8939982786"  # 替换为您的实际数据库ID

[env.staging]
name = "memos-cloudflare-staging"

[env.production]
name = "memos-cloudflare-production" 